import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import FooterFixed from './components/footer/FooterFixed'
import Categories from './components/Categories'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
          <div id="map"></div>
        <Navbar />
        <Categories />
        {children}
        <FooterFixed />
      </body>
    </html>
  )
} 
