const list = [
  { id: 11, name: "Cottage" },
  { id: 12, name: "A Frames" },
  { id: 13, name: "Huts" },
  { id: 14, name: "Tree Houses" },
  { id: 15, name: "Tents" },
  { id: 16, name: "Domes" },
  { id: 17, name: "Floating" },
  { id: 18, name: "Containers" },
  { id: 19, name: "Castles" },
  { id: 20, name: "Yurts" },
  { id: 21, name: "Pods" },
  { id: 22, name: "Campsites" },
  { id: 23, name: "RVs" },
  { id: 24, name: "Wine Cellar" },
  { id: 25, name: "Art House" },
  // Features (30-40)
  { id: 31, name: "Pets allowed" },
  { id: 32, name: "Breakfast" },
  { id: 33, name: "Outside Jacuzzi" },
  { id: 34, name: "Sauna" },
  { id: 35, name: "Bar / Restaurant" },
  // Scenic views (40-50)
  { id: 41, name: "Mountain view" },
  { id: 42, name: "Lake view" },
  { id: 43, name: "Sea view" },
  { id: 44, name: "Valley view" },
  { id: 45, name: "Forest view" },
  { id: 46, name: "Garden view" },
  { id: 47, name: "River view" },
  // Amenities of homes (50-80)
  { id: 51, name: "WiFi" },
  { id: 52, name: "Toilets" },
  { id: 53, name: "Campfires" },
  { id: 54, name: "Hot Water" },
  { id: 55, name: "Showers" },
  { id: 56, name: "Bathtub" },
  { id: 57, name: "Picnic table" },
  { id: 58, name: "Swim Seat" },
  { id: 59, name: "Hammock" },
  { id: 60, name: "Kitchen" },
  { id: 61, name: "Refrigerator" },
  { id: 62, name: "Microwave" },
  { id: 63, name: "Cooking equipment" },
  { id: 64, name: "BBQ grill" },
  { id: 65, name: "Air conditioning" },
  { id: 66, name: "Indoor Fireplace" },
  { id: 67, name: "Heating" },
  { id: 68, name: "Toaster" },
  { id: 69, name: "TV" },
  { id: 70, name: "Coffee Machine" },
  { id: 71, name: "Hair Dryer" },
  { id: 72, name: "Iron" },
  { id: 73, name: "First Aid Kit" },
  // Activities (80-100)
  { id: 80, name: "Hiking" },
  { id: 81, name: "Swimming" },
  { id: 82, name: "Fishing" },
  { id: 84, name: "Biking" },
  { id: 85, name: "Wildlife watching" },
  { id: 86, name: "Boating" },
  { id: 87, name: "Off-roading (OHV)" },
  { id: 88, name: "Snow sports" },
  { id: 89, name: "Board Games" },
  { id: 90, name: "Outdoor Activities" },
  { id: 91, name: "Walking Tours" },

  { id: 400, name: "All" },
];

export default list;
